### ISSUE TITLE
Security concern using v1/chain/get_raw_abi

### ISSUE THREAD

**Issue by samkirton** [EOSIO/eosio-java#82]
The SDK uses the chain http request `v1/chain/get_raw_abi` to get abi bytes for a given Map. This is vulnerable to man-in-the-middle attacks, it would make more sense to provide an empty interface, and have all users use local byte writing from https://github.com/EOSIO/eosio-java-android-abieos-serialization-provider

**Comment by DanteNguyen1008** [comment]
@samkirton Thanks for your concern. We don't quite understand your statement so we would love to have more detail about it. 
BTW:
- We provide empty interfaces for serialization provider and ABI Providers  to serialize transaction if you don't want to use `get_raw_abi` and https://github.com/EOSIO/eosio-java-android-abieos-serialization-provider. 
- Any network call is vulnerable to main-in-the-middle attacks if client does not have protection technique like Certificate Pinning. 
- EOSIO also has [eosio.assert](https://github.com/EOSIO/eosio.assert/) to prevent men-in-the-middle-attacks but you have to use `get_raw_abi`.

**Comment by brandonfancher** [comment]
@samkirton: As @DanteNguyen1008 mentioned, `eosio.assert` is a proposed solution to these types of attacks. It is a contract that EOSIO chains, such as mainnet, could deploy that would allow developers to include the the hash of the ABI they received _in_ the transaction and the chain would verify that it matches the hash of the one actually on the chain.

In that scenario, if a call to get abis from a chain were MITM attacked and the ABI changed, when the transaction actually gets broadcast to the chain, the chain would reject it.

Just keep in mind that it's a recent proposal and isn't actually deployed to any chain yet, that we're aware of.

More information on the `eosio.assert` contract can be found here: https://medium.com/eosio/eosio-labs-release-the-assert-manifest-security-model-cdd296a58710

**Comment by samkirton** [comment]
It sounds like `eosio.assert` is the answer to MITM then, @DanteNguyen1008 certificate pinning isn't an option for fully decentralised wallets or apps that can communicate with any node. I still think it makes more sense to only provide `IABIProvider` with this repository, and remove `ABIProviderImpl`, or only implement it with sample apps. In my opinion, a default implementation in a core module should not have any security caveats.

> Any network call is vulnerable to main-in-the-middle attacks if client does not have protection technique like Certificate Pinning.
@DanteNguyen1008 Signing locally written abi bytes and posting them with push_transaction is not vulnerable to MITM. However, the response of `get_raw_abi` can be intercepted, spoofed, unknowingly signed by the device, and pushed to the network (assuming eosio.assert isn't used).

**Comment by brandonfancher** [comment]
@samkirton We're still trying to understand where you're coming from fully. Are you proposing that (absent `eosio.assert`) apps should use their own, trusted, ABIs instead of fetching them from a chain? For many apps that only operate with a known subset of contracts, that is probably the safest way to proceed. But for a wallet that might want to sign any transaction a user sends to them, that wouldn't work. New contracts are deployed all the time.

If you truly want to be able to sign transactions for any contract on the chain, you have to fetch the ABIs from somewhere, don't you? Where else would you get those from than an RPC call to a node?

For that app that wants to provide their own ABIs for the sake of security, they can easily instantiate the core EOSIO SDK for Java transaction with their own ABI provider.

**Comment by brandonfancher** [comment]
FWIW, `eosjs` also gets ABIs from nodes via RPC, by default. It, too, can be overridden with a dev-provided ABI Provider.

**Comment by samkirton** [comment]
Ahh sorry I was getting confused with `abi_json_to_bin`
